# Generated by Django 3.2.13 on 2022-05-14 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BloodBankApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donate',
            name='phno',
        ),
    ]
