# Generated by Django 3.2.13 on 2022-05-14 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BloodBankApp', '0002_remove_donate_phno'),
    ]

    operations = [
        migrations.AddField(
            model_name='donate',
            name='phno',
            field=models.BigIntegerField(default=9656718864),
            preserve_default=False,
        ),
    ]
